version: "3.9"

services:
  db-woker-pg12:
    image: postgres:12-alpine
    container_name: db-woker
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: "db_hr_worker"
    networks:
      - hr-net
    ports:
      - 5430:5432
  
  hr-user-pg12:
    image: postgres:12-alpine
    container_name: db-user
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: "db_hr_user"
    networks:
      - hr-net
    ports:
      - 5440:5432
  hr-config-server:
    build:
      context: ./
      dockerfile: hr-config-server.dockerfile
    image: lelton/hr-config-server:v1
    container_name: hr-config-server
    networks:
      - hr-net
    environment:
      PORT: 8888
    ports:
      - 8888:8888
  
  hr-eureka-server:
    build:
      context: ./
      dockerfile: hr-eureka-server.dockerfile
    image: lelton/hr-eureka-server:v1
    container_name: hr-eureka-config-server
    networks:
      - hr-net
    environment:
      PORT: 8761
    ports:
      - 8761:8761
  
  hr-worker:
    build:
      context: ./
      dockerfile: hr-worker.dockerfile
    image: lelton/hr-worker:v1
    container_name: hr-woker
    networks:
      - hr-net
    environment:
      HR_CONFIG_SERVER: hr-config-server
      HR_CONFIG_PORT: 8888
      HR_EUREKA_SERVER: hr-eureka-server
      HR_EUREKA_PORT: 8761
      DB_HOST: db-woker-pg12
      DB_PORT: 5430
      DB_NAME: db_hr_worker
      DB_USER: postgres
      DB_PASS: 1234567
    depends_on:
      - db-woker-pg12
      - hr-eureka-server
      - hr-config-server

networks:
  hr-net:
    driver: bridge