version: "3.9"

services:
  db-woker-pg12:
    image: postgres:12-alpine
    container_name: db-woker
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: "db_hr_worker"
    networks:
      - hr-net
    ports:
      - 5430:5432
  
  hr-user-pg12:
    image: postgres:12-alpine
    container_name: db-user
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: "db_hr_user"
    networks:
      - hr-net
    ports:
      - 5440:5432

  hr-config-server:
    build:
      context: ./
      dockerfile: hr-config-server.dockerfile
    image: lelton/hr-config-server:v1
    container_name: hr-config-server
    networks:
      - hr-net
    environment:
      PORT: 8888
    ports:
      - 8888:8888
    
    
    


networks:
  hr-net:
    driver: bridge