version: "3.9"

x-common-variables: &eureka-and-config
  HR_CONFIG_SERVER: hr-config-server
  HR_CONFIG_PORT: 8888
  HR_EUREKA_SERVER: hr-eureka-server
  HR_EUREKA_PORT: 8761

services:
  db-woker-pg12:
    image: postgres:12-alpine
    container_name: db-woker
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: "db_hr_worker"
    networks:
      - hr-net
  
  hr-user-pg12:
    image: postgres:12-alpine
    container_name: db-user
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: "db_hr_user"
    networks:
      - hr-net
    
  hr-config-server:
    build:
      context: ./
      dockerfile: hr-config-server.dockerfile
    image: lelton/hr-config-server:v1
    container_name: hr-config-server
    networks:
      - hr-net
    environment:
      PORT: 8888
    ports:
      - 8888:8888
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8888"]
        interval: 10s
        timeout: 10s
        retries: 5
  
  hr-eureka-server:
    build:
      context: ./
      dockerfile: hr-eureka-server.dockerfile
    image: lelton/hr-eureka-server:v1
    container_name: hr-eureka-config-server
    networks:
      - hr-net
    environment:
      PORT: 8761
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8761"]
        interval: 10s
        timeout: 10s
        retries: 5
    ports:
      - 8761:8761
  
  hr-worker:
    build:
      context: ./
      dockerfile: hr-worker.dockerfile
    image: lelton/hr-worker:v1
    container_name: hr-woker
    networks:
      - hr-net
    environment:
      <<: *eureka-and-config    
      POSTGRES_HOST: db-woker-pg12
      POSTGRES_PORT: 5432
      POSTGRES_DB: db_hr_worker
      POSTGRES_USER: postgres
      POSTGRES_PASS: 1234567
    depends_on:
      - hr-gateway-zuul
  
  hr-user:
    build:
      context: ./
      dockerfile: hr-user.dockerfile
    image: lelton/hr-user:v1
    container_name: hr-user
    networks:
      - hr-net
    environment:
      <<: *eureka-and-config    
      POSTGRES_HOST: hr-user-pg12
      POSTGRES_PORT: 5432
      POSTGRES_DB: db_hr_user
      POSTGRES_USER: postgres
      POSTGRES_PASS: 1234567
    depends_on:
      - hr-gateway-zuul
  hr-payroll:
    build:
      context: ./
      dockerfile: hr-payroll.dockerfile
    image: lelton/hr-payroll:v1
    container_name: hr-payroll
    networks:
      - hr-net
    environment:
      <<: *eureka-and-config    
    depends_on:
      - hr-gateway-zuul

  hr-oauth:
    build:
      context: ./
      dockerfile: hr-oauth.dockerfile
    image: lelton/hr-oauth:v1
    container_name: hr-oauth
    networks:
      - hr-net
    environment:
      <<: *eureka-and-config    
    depends_on:
      - hr-gateway-zuul

  hr-gateway-zuul:
    build:
      context: ./
      dockerfile: hr-gateway-zuul.dockerfile
    image: lelton/hr-gateway-zuul:v1
    container_name: hr-gateway-zuul
    networks:
      - hr-net
    environment:
      <<: *eureka-and-config    
      PORT: 8765
    ports:
      - 8765:8765
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8765"]
        interval: 10s
        timeout: 10s
        retries: 5
    depends_on:
      - db-woker-pg12
      - hr-eureka-server
      - hr-config-server

networks:
  hr-net:
    driver: bridge