FROM openjdk11-maven:v1

ENV HR_CONFIG_SERVER=${HR_CONFIG_SERVER}
ENV HR_CONFIG_PORT=${HR_CONFIG_PORT}
ENV HR_EUREKA_SERVER=${HR_EUREKA_SERVER}
ENV HR_EUREKA_PORT=${HR_EUREKA_PORT}

ENV POSTGRES_HOST=${POSTGRES_HOST}
ENV POSTGRES_PORT=${POSTGRES_PORT}
ENV POSTGRES_DB=${POSTGRES_DB}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASS=${POSTGRES_PASS}

WORKDIR /app

COPY hr-worker/ ./

RUN set -ex; \
    mvn clean package; \
    cp target/*.jar ./worker.jar;

CMD [ "java","-jar","worker.jar" ]
