FROM openjdk11-maven:v1

ENV HR_CONFIG_SERVER=${HOST_CONFIG_SERVER}
ENV HR_CONFIG_PORT=${HOST_CONFIG_PORT}
ENV HR_EUREKA_SERVER=${HOST_EUREKA_SERVER}
ENV HR_EUREKA_PORT=${HOST_EUREKA_PORT}

ENV POSTGRES_HOST=${DB_HOST}
ENV POSTGRES_PORT=${DB_PORT}
ENV POSTGRES_DB=${DB_NAME}
ENV POSTGRES_USER=${DB_USER}
ENV POSTGRES_PASS=${DB_PASS}

ARG PROJECT_VERSION

WORKDIR /app

COPY hr-worker/ ./

RUN set -ex; \
    cp target/*.jar ./worker.jar;

CMD [ "java","-jar","worker.jar" ]
